name: Go CI

on:
  push:
    branches:
      - dev

jobs:
  lint:
    name: Run Go Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.0

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest